"""create football world tables

Revision ID: 61162acbecd9
Revises: 
Create Date: 2026-08-24 15:35:46.874511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '61162acbecd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('competition_type', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=16), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('prestige', sa.Float(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fifa_rank', sa.Integer(), nullable=True),
    sa.Column('fifa_points', sa.Float(), nullable=True),
    sa.Column('national_strength', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tactical_quality', sa.Float(), nullable=False),
    sa.Column('player_development', sa.Float(), nullable=False),
    sa.Column('game_management', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('adaptability', sa.Float(), nullable=False),
    sa.Column('tactical_style', sa.String(length=50), nullable=False),
    sa.Column('youth_preference', sa.Float(), nullable=False),
    sa.Column('discipline', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_key', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('current_strength', sa.Float(), nullable=False),
    sa.Column('prestige', sa.Float(), nullable=False),
    sa.Column('financial_strength', sa.Float(), nullable=False),
    sa.Column('european_performance', sa.Float(), nullable=False),
    sa.Column('global_reputation', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=16), nullable=False),
    sa.Column('league_code', sa.String(length=16), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('current_strength', sa.Float(), nullable=False),
    sa.Column('prestige', sa.Float(), nullable=False),
    sa.Column('financial_power', sa.Float(), nullable=False),
    sa.Column('academy_quality', sa.Float(), nullable=False),
    sa.Column('facilities', sa.Float(), nullable=False),
    sa.Column('fan_pressure', sa.Float(), nullable=False),
    sa.Column('squad_depth', sa.Float(), nullable=False),
    sa.Column('uefa_coefficient_raw', sa.Float(), nullable=False),
    sa.Column('uefa_coefficient_normalized', sa.Float(), nullable=False),
    sa.Column('domestic_reputation', sa.Float(), nullable=False),
    sa.Column('international_reputation', sa.Float(), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['league_code'], ['leagues.code'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generic_squad_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generic_squad_players')
    op.drop_table('clubs')
    op.drop_table('leagues')
    op.drop_table('source_values')
    op.drop_table('managers')
    op.drop_table('countries')
    op.drop_table('competitions')
    # ### end Alembic commands ###
