"""add player engine fields

Revision ID: 62cc621570b9
Revises: be73f8b445d5
Create Date: 2026-08-24 16:05:13.944877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '62cc621570b9'
down_revision: Union[str, None] = 'be73f8b445d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing rows are generated Phase 2 seed data. They are intentionally
    # rebuilt by the seed script because the old scalar schema cannot be
    # losslessly mapped to the v1.3 internal attribute model.
    op.execute("DELETE FROM club_memberships")
    op.execute("DELETE FROM players")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('internal_attributes', sa.JSON(), nullable=False))
    op.add_column('players', sa.Column('development_profile', sa.String(length=20), nullable=False))
    op.add_column('players', sa.Column('role_familiarity', sa.JSON(), nullable=False))
    op.add_column('players', sa.Column('traits', sa.JSON(), nullable=False))
    op.add_column('players', sa.Column('personality', sa.JSON(), nullable=False))
    op.drop_column('players', 'shooting')
    op.drop_column('players', 'crossing')
    op.drop_column('players', 'creativity')
    op.drop_column('players', 'strength')
    op.drop_column('players', 'defending')
    op.drop_column('players', 'work_rate')
    op.drop_column('players', 'composure')
    op.drop_column('players', 'acceleration')
    op.drop_column('players', 'leadership')
    op.drop_column('players', 'passing')
    op.drop_column('players', 'decision_making')
    op.drop_column('players', 'ball_control')
    op.drop_column('players', 'dribbling')
    op.drop_column('players', 'pace')
    op.drop_column('players', 'agility')
    op.drop_column('players', 'stamina')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('stamina', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('agility', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('pace', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('dribbling', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('ball_control', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('decision_making', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('passing', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('leadership', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('acceleration', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('composure', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('work_rate', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('defending', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('strength', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('creativity', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('crossing', sa.FLOAT(), nullable=False))
    op.add_column('players', sa.Column('shooting', sa.FLOAT(), nullable=False))
    op.drop_column('players', 'personality')
    op.drop_column('players', 'traits')
    op.drop_column('players', 'role_familiarity')
    op.drop_column('players', 'development_profile')
    op.drop_column('players', 'internal_attributes')
    # ### end Alembic commands ###
