"""replace generic players with shared player domain

Revision ID: be73f8b445d5
Revises: 61162acbecd9
Create Date: 2026-08-24 15:46:52.247080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'be73f8b445d5'
down_revision: Union[str, None] = '61162acbecd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Phase 2 generic players are generated seed data; the seed script rebuilds them
    # with stable Player identities after this schema transition.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=16), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('preferred_foot', sa.String(length=8), nullable=False),
    sa.Column('primary_position', sa.String(length=3), nullable=False),
    sa.Column('secondary_positions', sa.JSON(), nullable=False),
    sa.Column('passing', sa.Float(), nullable=False),
    sa.Column('dribbling', sa.Float(), nullable=False),
    sa.Column('shooting', sa.Float(), nullable=False),
    sa.Column('ball_control', sa.Float(), nullable=False),
    sa.Column('crossing', sa.Float(), nullable=False),
    sa.Column('defending', sa.Float(), nullable=False),
    sa.Column('pace', sa.Float(), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('stamina', sa.Float(), nullable=False),
    sa.Column('agility', sa.Float(), nullable=False),
    sa.Column('decision_making', sa.Float(), nullable=False),
    sa.Column('composure', sa.Float(), nullable=False),
    sa.Column('creativity', sa.Float(), nullable=False),
    sa.Column('work_rate', sa.Float(), nullable=False),
    sa.Column('leadership', sa.Float(), nullable=False),
    sa.Column('current_ability', sa.Float(), nullable=False),
    sa.Column('potential', sa.Float(), nullable=False),
    sa.Column('development_rate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('morale', sa.Float(), nullable=False),
    sa.Column('form', sa.Float(), nullable=False),
    sa.Column('fitness', sa.Float(), nullable=False),
    sa.Column('fatigue', sa.Float(), nullable=False),
    sa.Column('happiness', sa.Float(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('generic_squad_players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_squad_players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.VARCHAR(length=3), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('club_memberships')
    op.drop_table('players')
    # ### end Alembic commands ###
