"""store player archetype

Revision ID: e2c31d282bfb
Revises: 62cc621570b9
Create Date: 2026-08-24 16:18:45.833985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e2c31d282bfb'
down_revision: Union[str, None] = '62cc621570b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('archetype', sa.String(length=32), server_default='BALANCED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'archetype')
    # ### end Alembic commands ###
